[2023-01-26 16:48:26,975] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-26 16:48:26,992] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-26 16:48:26,992] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:48:26,992] {taskinstance.py:1377} INFO - Starting attempt 7 of 9
[2023-01-26 16:48:26,993] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:48:27,017] {taskinstance.py:1397} INFO - Executing <Task(GeneratesatelliteDataOperator): generate_platzi_data> on 2023-01-01 00:00:00+00:00
[2023-01-26 16:48:27,024] {standard_task_runner.py:52} INFO - Started process 208 to run task
[2023-01-26 16:48:27,029] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'generate_platzi_data', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '579', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmpfser2x4y', '--error-file', '/tmp/tmpzecn90i1']
[2023-01-26 16:48:27,031] {standard_task_runner.py:80} INFO - Job 579: Subtask generate_platzi_data
[2023-01-26 16:48:27,131] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-01T00:00:00+00:00 [running]> on host 1dac8e18bdf5
[2023-01-26 16:48:27,255] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=generate_platzi_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:00:00+00:00
[2023-01-26 16:48:27,258] {logging_mixin.py:115} INFO - La fecha l√≥gica es: 20230101
[2023-01-26 16:48:27,268] {logging_mixin.py:115} INFO - archivo creado en: /tmp/platzi_data_20230101.csv
[2023-01-26 16:48:27,291] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Respuesta_Nasa, task_id=generate_platzi_data, execution_date=20230101T000000, start_date=20230126T164826, end_date=20230126T164827
[2023-01-26 16:48:27,321] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-26 16:48:27,397] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
