[2023-01-24 02:43:18,170] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Nasa scheduled__2023-01-01T01:25:00+00:00 [queued]>
[2023-01-24 02:43:18,190] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Nasa scheduled__2023-01-01T01:25:00+00:00 [queued]>
[2023-01-24 02:43:18,191] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 02:43:18,191] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-01-24 02:43:18,191] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 02:43:18,215] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): Leer_Datos_Respuesta_Nasa> on 2023-01-01 01:25:00+00:00
[2023-01-24 02:43:18,222] {standard_task_runner.py:52} INFO - Started process 1683 to run task
[2023-01-24 02:43:18,225] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'Leer_Datos_Respuesta_Nasa', 'scheduled__2023-01-01T01:25:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmpmo1tdtfz', '--error-file', '/tmp/tmp2ml316b9']
[2023-01-24 02:43:18,227] {standard_task_runner.py:80} INFO - Job 267: Subtask Leer_Datos_Respuesta_Nasa
[2023-01-24 02:43:18,336] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Nasa scheduled__2023-01-01T01:25:00+00:00 [running]> on host fd9891b969b0
[2023-01-24 02:43:18,572] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=Leer_Datos_Respuesta_Nasa
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T01:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T01:25:00+00:00
[2023-01-24 02:43:18,576] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-24 02:43:18,576] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ls /tmp && head /tmp/response_20230101.txt']
[2023-01-24 02:43:18,596] {subprocess.py:85} INFO - Output:
[2023-01-24 02:43:18,601] {subprocess.py:92} INFO - ***tmp2aw9daa5
[2023-01-24 02:43:18,601] {subprocess.py:92} INFO - ***tmp80svek5n
[2023-01-24 02:43:18,601] {subprocess.py:92} INFO - ***tmpc1ke85zl
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - ***tmpd2p6lr32
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - ***tmpqjzgpv3j
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - ***tmpr1ygmtvb
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - ***tmpxo_v7qup
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - ***tmpxqzxkt25
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - pymp-igsi0xnb
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - response_20230101.txt
[2023-01-24 02:43:18,602] {subprocess.py:92} INFO - spacex_20230101.json
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmp0vff_rcn
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmp2ml316b9
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmpd200ak8q
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmpg0rggbcr
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmphg5k59k_
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmpinycs6yv
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmpnvc2r2ky
[2023-01-24 02:43:18,603] {subprocess.py:92} INFO - tmpp7tc_q2q
[2023-01-24 02:43:18,604] {subprocess.py:92} INFO - tmpv9if5f0a
[2023-01-24 02:43:18,604] {subprocess.py:92} INFO - tmpxqo4lqui
[2023-01-24 02:43:18,604] {subprocess.py:92} INFO - tmpxt_x3ssz
[2023-01-24 02:43:18,607] {subprocess.py:92} INFO - Confirmaci√≥n de la NASA, pueden proceder
[2023-01-24 02:43:18,607] {subprocess.py:96} INFO - Command exited with return code 0
[2023-01-24 02:43:18,692] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Respuesta_Nasa, task_id=Leer_Datos_Respuesta_Nasa, execution_date=20230101T012500, start_date=20230124T024318, end_date=20230124T024318
[2023-01-24 02:43:18,762] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-24 02:43:19,032] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
