[2023-01-26 16:39:37,191] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-26 16:39:37,209] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-26 16:39:37,209] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:39:37,210] {taskinstance.py:1377} INFO - Starting attempt 6 of 8
[2023-01-26 16:39:37,210] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:39:37,235] {taskinstance.py:1397} INFO - Executing <Task(GeneratesatelliteDataOperator): generate_platzi_data> on 2023-01-02 00:00:00+00:00
[2023-01-26 16:39:37,242] {standard_task_runner.py:52} INFO - Started process 320 to run task
[2023-01-26 16:39:37,247] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'generate_platzi_data', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '548', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmpepqkyhxb', '--error-file', '/tmp/tmp_4zv6qfy']
[2023-01-26 16:39:37,248] {standard_task_runner.py:80} INFO - Job 548: Subtask generate_platzi_data
[2023-01-26 16:39:37,336] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-02T00:00:00+00:00 [running]> on host 1e10284898e4
[2023-01-26 16:39:37,442] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=generate_platzi_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-26 16:39:37,443] {logging_mixin.py:115} INFO - La fecha l√≥gica es: 20230102
[2023-01-26 16:39:37,453] {logging_mixin.py:115} INFO - archivo creado en: /tmp/platzi_data_20230102.csv
[2023-01-26 16:39:37,472] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Respuesta_Nasa, task_id=generate_platzi_data, execution_date=20230102T000000, start_date=20230126T163937, end_date=20230126T163937
[2023-01-26 16:39:37,500] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-26 16:39:37,568] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
