[2023-01-26 18:08:43,643] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-26 18:08:43,658] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-26 18:08:43,658] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 18:08:43,658] {taskinstance.py:1377} INFO - Starting attempt 10 of 12
[2023-01-26 18:08:43,658] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 18:08:43,672] {taskinstance.py:1397} INFO - Executing <Task(GeneratesatelliteDataOperator): generate_platzi_data> on 2023-01-03 00:00:00+00:00
[2023-01-26 18:08:43,677] {standard_task_runner.py:52} INFO - Started process 994 to run task
[2023-01-26 18:08:43,680] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'generate_platzi_data', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '666', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmpz1asil9q', '--error-file', '/tmp/tmpmzflioel']
[2023-01-26 18:08:43,681] {standard_task_runner.py:80} INFO - Job 666: Subtask generate_platzi_data
[2023-01-26 18:08:43,745] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.generate_platzi_data scheduled__2023-01-03T00:00:00+00:00 [running]> on host da6de88268cf
[2023-01-26 18:08:43,822] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=frandak2@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=generate_platzi_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-03T00:00:00+00:00
[2023-01-26 18:08:43,823] {logging_mixin.py:115} INFO - La fecha l√≥gica es: 20230103
[2023-01-26 18:08:43,827] {logging_mixin.py:115} INFO - archivo creado en: /tmp/platzi_data_20230103.csv
[2023-01-26 18:08:43,841] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Respuesta_Nasa, task_id=generate_platzi_data, execution_date=20230103T000000, start_date=20230126T180843, end_date=20230126T180843
[2023-01-26 18:08:43,891] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-26 18:08:43,960] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
