[2023-01-24 03:41:47,020] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Esperando_el_fichero scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-24 03:41:47,033] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Esperando_el_fichero scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-24 03:41:47,033] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 03:41:47,034] {taskinstance.py:1377} INFO - Starting attempt 2 of 4
[2023-01-24 03:41:47,034] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-24 03:41:47,051] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): Esperando_el_fichero> on 2023-01-03 00:00:00+00:00
[2023-01-24 03:41:47,056] {standard_task_runner.py:52} INFO - Started process 2608 to run task
[2023-01-24 03:41:47,059] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'Esperando_el_fichero', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '438', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmp4f26tviy', '--error-file', '/tmp/tmposd34ra8']
[2023-01-24 03:41:47,061] {standard_task_runner.py:80} INFO - Job 438: Subtask Esperando_el_fichero
[2023-01-24 03:41:47,130] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.Esperando_el_fichero scheduled__2023-01-03T00:00:00+00:00 [running]> on host fd9891b969b0
[2023-01-24 03:41:47,208] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=Esperando_el_fichero
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-03T00:00:00+00:00
[2023-01-24 03:41:47,219] {base.py:68} INFO - Using connection ID 'fs_default' for task execution.
[2023-01-24 03:41:47,219] {filesystem.py:58} INFO - Poking for file /tmp/response_20230103.txt
[2023-01-24 03:41:47,220] {filesystem.py:63} INFO - Found File /tmp/response_20230103.txt last modified: 20230124034146
[2023-01-24 03:41:47,220] {base.py:301} INFO - Success criteria met. Exiting.
[2023-01-24 03:41:47,235] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Respuesta_Nasa, task_id=Esperando_el_fichero, execution_date=20230103T000000, start_date=20230124T034147, end_date=20230124T034147
[2023-01-24 03:41:47,271] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-24 03:41:47,328] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
