[2023-01-26 16:48:28,461] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Satelite scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-26 16:48:28,474] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Satelite scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-26 16:48:28,474] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:48:28,474] {taskinstance.py:1377} INFO - Starting attempt 10 of 12
[2023-01-26 16:48:28,474] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:48:28,495] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): Leer_Datos_Respuesta_Satelite> on 2023-01-01 00:00:00+00:00
[2023-01-26 16:48:28,501] {standard_task_runner.py:52} INFO - Started process 218 to run task
[2023-01-26 16:48:28,505] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'Leer_Datos_Respuesta_Satelite', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '581', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmpthpuiawl', '--error-file', '/tmp/tmpbbdthxv2']
[2023-01-26 16:48:28,507] {standard_task_runner.py:80} INFO - Job 581: Subtask Leer_Datos_Respuesta_Satelite
[2023-01-26 16:48:28,588] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Satelite scheduled__2023-01-01T00:00:00+00:00 [running]> on host 1dac8e18bdf5
[2023-01-26 16:48:28,710] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=Leer_Datos_Respuesta_Satelite
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:00:00+00:00
[2023-01-26 16:48:28,712] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-26 16:48:28,712] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ls /tmp && head /tmp/platzi_data_20230101.csv']
[2023-01-26 16:48:28,724] {subprocess.py:85} INFO - Output:
[2023-01-26 16:48:28,728] {subprocess.py:92} INFO - ***tmp3z605573
[2023-01-26 16:48:28,728] {subprocess.py:92} INFO - platzi_data_20230101.csv
[2023-01-26 16:48:28,729] {subprocess.py:92} INFO - platzi_data_20230102.csv
[2023-01-26 16:48:28,729] {subprocess.py:92} INFO - platzi_data_20230103.csv
[2023-01-26 16:48:28,729] {subprocess.py:92} INFO - pymp-cesmfe3z
[2023-01-26 16:48:28,729] {subprocess.py:92} INFO - response_20230101.txt
[2023-01-26 16:48:28,729] {subprocess.py:92} INFO - response_20230102.txt
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - response_20230103.txt
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - spacex_20230101.json
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - spacex_20230102.json
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - spacex_20230103.json
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - tmpbbdthxv2
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - tmpbzjoiqz9
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - tmpnvc2r2ky
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - tmpwbsi4utb
[2023-01-26 16:48:28,730] {subprocess.py:92} INFO - ,student,timestamp
[2023-01-26 16:48:28,731] {subprocess.py:92} INFO - 0,Maria Cruz,20230101
[2023-01-26 16:48:28,731] {subprocess.py:92} INFO - 1,Daniel Crema,20230101
[2023-01-26 16:48:28,731] {subprocess.py:92} INFO - 2,Elon Musk,20230101
[2023-01-26 16:48:28,731] {subprocess.py:92} INFO - 3,Karol Castrejon,20230101
[2023-01-26 16:48:28,731] {subprocess.py:92} INFO - 4,Freddy Vega,20230101
[2023-01-26 16:48:28,731] {subprocess.py:96} INFO - Command exited with return code 0
[2023-01-26 16:48:28,769] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Respuesta_Nasa, task_id=Leer_Datos_Respuesta_Satelite, execution_date=20230101T000000, start_date=20230126T164828, end_date=20230126T164828
[2023-01-26 16:48:28,797] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-26 16:48:28,847] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
