[2023-01-26 16:39:33,347] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Nasa scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-26 16:39:33,365] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Nasa scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-26 16:39:33,365] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:39:33,365] {taskinstance.py:1377} INFO - Starting attempt 6 of 8
[2023-01-26 16:39:33,365] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-26 16:39:33,390] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): Leer_Datos_Respuesta_Nasa> on 2023-01-02 00:00:00+00:00
[2023-01-26 16:39:33,397] {standard_task_runner.py:52} INFO - Started process 287 to run task
[2023-01-26 16:39:33,401] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Respuesta_Nasa', 'Leer_Datos_Respuesta_Nasa', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/00-ETL_spaceX.py', '--cfg-path', '/tmp/tmpxppy519l', '--error-file', '/tmp/tmpr4ty5ka8']
[2023-01-26 16:39:33,402] {standard_task_runner.py:80} INFO - Job 542: Subtask Leer_Datos_Respuesta_Nasa
[2023-01-26 16:39:33,480] {task_command.py:371} INFO - Running <TaskInstance: Respuesta_Nasa.Leer_Datos_Respuesta_Nasa scheduled__2023-01-02T00:00:00+00:00 [running]> on host 1e10284898e4
[2023-01-26 16:39:33,569] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=Respuesta_Nasa
AIRFLOW_CTX_TASK_ID=Leer_Datos_Respuesta_Nasa
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-26 16:39:33,571] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-26 16:39:33,571] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ls /tmp && head /tmp/response_20230102.txt']
[2023-01-26 16:39:33,582] {subprocess.py:85} INFO - Output:
[2023-01-26 16:39:33,586] {subprocess.py:92} INFO - ***tmpkzj87580
[2023-01-26 16:39:33,586] {subprocess.py:92} INFO - pymp-a0rn_v15
[2023-01-26 16:39:33,586] {subprocess.py:92} INFO - response_20230101.txt
[2023-01-26 16:39:33,586] {subprocess.py:92} INFO - response_20230102.txt
[2023-01-26 16:39:33,586] {subprocess.py:92} INFO - response_20230103.txt
[2023-01-26 16:39:33,586] {subprocess.py:92} INFO - tmpdm_1na1d
[2023-01-26 16:39:33,586] {subprocess.py:92} INFO - tmpnvc2r2ky
[2023-01-26 16:39:33,587] {subprocess.py:92} INFO - tmpr4ty5ka8
[2023-01-26 16:39:33,587] {subprocess.py:92} INFO - tmpvhccic1w
[2023-01-26 16:39:33,587] {subprocess.py:92} INFO - Confirmaci√≥n de la NASA, pueden proceder
[2023-01-26 16:39:33,587] {subprocess.py:96} INFO - Command exited with return code 0
[2023-01-26 16:39:33,620] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Respuesta_Nasa, task_id=Leer_Datos_Respuesta_Nasa, execution_date=20230102T000000, start_date=20230126T163933, end_date=20230126T163933
[2023-01-26 16:39:33,652] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-26 16:39:33,705] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
